### ISSUE TITLE
请问模板具体使用的是哪个版本的ctexbook包？

### ISSUE THREAD

**Issue by liudonglei** [BIT-thesis/LaTeX-template#12]
在 windows 7 系统下：
使用最新的texlive2017 编译，每小节标题不换行； ctexbook是2017年的。
使用CTeX_2.9.2.164_Full编译，跟提供的样本一样，ctexbook 是2011年的。

不知道是不是ctexbook版本的问题还是中文字体的问题？

**Comment by y-yating** [comment]
我使用的是CTeX_2.9.2.164_Full

**Comment by qiuzhu** [comment]
@liudonglei 可以fork我的另一个repo，用最新的编译套装(texlive或者miktex)即可通过，ctex套装实在太老旧了，欢迎pr

_Sent from my HUAWEI EVA-DL00 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by y-yating** [comment]
已更新模板
