### ISSUE TITLE
公式中无法显示矩阵、向量等粗体符号？

### ISSUE THREAD

**Issue by Chengsheng2008** [BIT-thesis/LaTeX-template#15]
很感谢能提供该模板，做的很不错！有两个小问题：
1）公式中使用\mathbf{x}指令（字符加粗）表示矩阵、向量变量时，黑体效果无法显示，感觉是“math packages -- conflict with xunicode”冲突，但没能解决，请教下？谢谢
2）北理工的英文有书写错误“Institute”。

**Comment by qiuzhu** [comment]
这个模板基于Ctex旧的宏包设置，建议还是更新，或者我的另一个repo

**Comment by y-yating** [comment]
模板已更新~

**Comment by y-yating** [comment]
才发现英文写错了，马上改正~~~谢谢~~
