### ISSUE TITLE
宋体更换问题

### ISSUE THREAD

**Issue by qiuzhu** [BIT-thesis/LaTeX-template#16]
宋体，其实不是免费的字体，强烈建议研究生院可以切换到谷歌发布的免费字体，思源宋体，该套字体的比较全，粗体，斜体都没问题

**Comment by yuzhangbit** [comment]
现在看来是暂时换不了啊　有没有linux下宋体字体的解决方案？

**Comment by qiuzhu** [comment]
我在Linux测试没有问题，搞全字体是没问题的，可以群里联系我：
170368921
