### ISSUE TITLE
建议更换编译套装

### ISSUE THREAD

**Issue by qiuzhu** [BIT-thesis/LaTeX-template#17]
- 目前ctex套装已经非常老旧，差不多是十年前的了，所以很多同学编译时出错，很多宏包均不支持，而且对中文的处理存在很大的问题，简直是入门的一个坑，强烈建议切换到texlive或者miktex套装，采用ctex宏包或者xecjk宏包的中午解决方案
- 如有必要，可以开展latex学习讲座，题案能通过就好了 

_Sent from my HUAWEI EVA-DL00 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by y-yating** [comment]
已经更新~谢谢

**Comment by ethan4335** [comment]
有详细步骤吗？

**Comment by ethan4335** [comment]
l.53 ...l:nnn { xeCJK } { l3-too-old } { expl3 } }
