### ISSUE TITLE
更新高亮问题

### ISSUE THREAD

**Issue by baicaihenxiao** [BIT-thesis/LaTeX-template#18]
以前用的latex模板对于新作的修改编译之后生成的pdf会直接跳到相应的页数并高亮显示修改的内容，但是这个模板每次生成的pdf都跳转的页数不对，不知道该怎么解决。

谢谢~

**Comment by y-yating** [comment]
请更新至最新版本再试下

**Comment by baicaihenxiao** [comment]
更新换了编译环境后我就编译不过了，算了，我还是用老版的吧/(ㄒoㄒ)/~~

**Comment by y-yating** [comment]
更新了环境后为何编译不过？ctex有卸除吗？

**Comment by y-yating** [comment]
建议能用新版就用新版吧~老版的模板以后应该不会维护了~（因为ctex确实太老了 -_-）~

**Comment by baicaihenxiao** [comment]
因为我还是用的ctex所以编译不过O(∩_∩)O哈哈~反正快毕业了~
作者大大辛苦啦~
ps:建议以后更新的时候可以用一下release功能，这样版本迭代更加明显些
