### ISSUE TITLE
关于算法的定义{algorithm}和{algorithmic}，如何实现

### ISSUE THREAD

**Issue by charlespc001** [BIT-thesis/LaTeX-template#19]
在cfg文件中，只给出了{algorithm}的定义，但我的code里还有{algorithmic}，这两个的结合，这个该怎么处理？如下：
\begin{algorithm}
\caption{xxx}\label{euclid}
\begin{algorithmic}[1]
{}
\State 

\end{algorithmic}
\end{algorithm}
谢谢!

**Comment by y-yating** [comment]
- 请下载最新模板~已删除cfg文件
- 另外需写算法的话~请在demo中导入
\usepackage{algorithm}
\usepackage{algorithmic}
