### ISSUE TITLE
如何实现表格的横向

### ISSUE THREAD

**Issue by charlespc001** [BIT-thesis/LaTeX-template#20]
将表格横向，用usepackage{landscape}宏包的\begin{landscape}  \end{landscape}，但是不起作用，在咱们这个模板里如何实现呢？另外，如果想添加一些usepackage的话，添加在demo.tex文件里，怎么同样不起作用，求指导，谢谢！

**Comment by y-yating** [comment]
对于横置...若使用landscape，应使用\usepackage{lscape} 导入宏包。
另外，添加一些宏包在demo.txt是可行的~
