### ISSUE TITLE
技术报告模板

### ISSUE THREAD

**Issue by yuzhangbit** [BIT-thesis/LaTeX-template#23]
在平时做研究或做项目的过程中大家都会有写文档，做记录总结的需求，请问有没有开发一个轻量化的北理工中英文技术报告模板的计划呢？

**Comment by y-yating** [comment]
这个目前暂时没有...感觉各个专业写的技术报告格式可能差别比较大，不像学位论文格式比较统一。没有官方的技术报告模板自己出一版模板怕误导大家~~ >_< 不过可以考虑做个简单的~哈哈

**Comment by yuzhangbit** [comment]
对，就是非常简单的那种～　:smile_cat:
